### ISSUE TITLE
research

### ISSUE THREAD

**Issue by alaestor** [alaestor/Rimworld-Teleporting#6]
Research defs and integration needs to be implemented

in rough order:
- [x] **Static Spatial Conduits**
    - [x] unlock constructable teleport console (misc tab)
    - [x] unlock teleport cartridge recipe
    - [x] unlock [Teleport pads](https://github.com/alaestor/Rimworld-Teleporting/issues/7) recipe
    - [x] unlock teleport receiver recipe
    - [x] unlock [linkable teleport belt ](https://github.com/alaestor/Rimworld-Teleporting/issues/9) recipe
- [x] **Dynamic Spatial Conduits**
    - [x] unlock portable teleport unit (SR) local 
    - [x] unlock portable teleport unit (LR) global
- [x] **Spatial Folding**
     - [x] unlock [local teleport belt](https://github.com/alaestor/Rimworld-Teleporting/issues/9) recipe
     - [x] unlock [global teleport belt](https://github.com/alaestor/Rimworld-Teleporting/issues/9) recipe
     - ~~unlock rescue teleport belt~~
- [x] **Mastery of Teleportation**
    - ~~Console cartridge loading, gizmo visibility, etc.~~ needs a replacement for refuelable
    - [x] Right-click console: SR / local teleport
    - [x] Right-click console: LR / global teleport
    - [x] unlock [advanced teleport belt ](https://github.com/alaestor/Rimworld-Teleporting/issues/9)

**Comment by alaestor** [comment]
Blocked by ~~teleport pads #7 , belts #9~~

Could do in pieces, but should probably do this last once everything else behaves properly
